### ISSUE TITLE
issue: running the project

### ISSUE THREAD

**Issue by HamidHabib** [archonic/limestone#22]
**Step 4** of the setup process triggers the following error.  `ERROR: No such service: webpack`

<img width="595" alt="Screen Shot 2020-03-16 at 6 30 31 PM" src="https://user-images.githubusercontent.com/9887370/76805100-55d4b900-67b4-11ea-9918-5b3d4966be41.png">

Although running **step 5** does seem to work to an extent it fails at later stages.
<img width="716" alt="Screen Shot 2020-03-16 at 6 33 04 PM" src="https://user-images.githubusercontent.com/9887370/76805207-96cccd80-67b4-11ea-9d94-ea3338b4610e.png">

I suspect it might be related to `step 4` not getting completed properly but I might be wrong. Any suggestions. 

**Note:** I am on Mac OS Mojave. Docker & Postgresql services are running
@archonic

**Comment by archonic** [comment]
Hi, thanks for catching this. The instructions are old now that there was a simplification of the docker-compose.yml config file. The `rails s` process can handle Webpack building and ActionCable connections so there's no need to run those standalone containers. You should be able to just omit step 4. Let me know how that goes.

**Comment by HamidHabib** [comment]
Hi, after running `rails s` it is complaining about `<main>': Cannot load database configuration: (NoMethodError)` database config not getting loaded properly. Although the in the .env file I added it as such `DATABASE_URL=postgresql://localhost/limestone`

**second issue:** setting the same env var `DATABASE_URL=postgresql://localhost/limestone` also doesnt work when running in docker `docker-compose up --build `

**Comment by archonic** [comment]
`rails s` wouldn't be a process you run yourself - that command is built into the start up of the web container when running `docker-compose up`. 

The DATABASE_URL doesn't look right there. The format is generally `<protocol>://<user>:<password>@<hostname>:<port>/<database>?encoding=utf8&pool=5&timeout=5000`. A few things to note:

- The question mark is required due to how database.yml is setup. It ensures different environments won't conflate even if the env var is the same across environments. This especially helps if you want to start a production environment locally for troubleshooting.
- The hostname relies upon docker compose networking. The hostname of the postgres container is `postgres` and not `localhost`.

The simplest working example would be `DATABASE_URL=postgresql://postgres:5432/<database>?` but that would be if you configured the postgres container for no authentication. You probably want `DATABASE_URL=postgresql://limestone:yourpassword@postgres:5432/<database>?`

**Comment by archonic** [comment]
@HamidHabib I've improved the read me instructions and followed them myself. Feel free to reopen if they don't work for you.
