### ISSUE TITLE
Credentials as plain text on the .env file

### ISSUE THREAD

**Issue by HatsuMora** [archonic/limestone#35]
some of the credentials are store on the .env file, what is your opinion about moving them to use the `rails credentials:edit` ?

I would be up to do it.

**Comment by archonic** [comment]
It would be preferable to use the `rails credentials:edit` convention as long as it still works well with Docker. I'd be happy to look at a PR!

**Comment by HatsuMora** [comment]
I did some googling and looks like people have solve this issue before, I will try to come with a PR next weekend

**Comment by archonic** [comment]
Hi @HatsuMora, was any progress made on this front?

As a side note, plaintext credentials in a .env file aren't necessarily a security issue as it's never committed to a repository or otherwise transmitted (hopefully). `.env` files are an established norm in Docker. I prefer the Rails credentials workflow but I wouldn't say moving to it is a requirement.

**Comment by archonic** [comment]
I welcome a PR for this in the future but I'm going to close it as it's not a priority.
