### ISSUE TITLE
Transparent Gravatar profiles show underlying avatar color/text

### ISSUE THREAD

**Issue by aeksco** [archonic/limestone#7]
See attached image - more my problem as a result of having a transparent profile pic, but should be addressed. I think if a Gravatar pic is detected, we should adjust the CSS to include a sane background color option with no initials. 

![Screenshot from 2019-06-23 15-01-43](https://user-images.githubusercontent.com/4616233/59980759-424f4580-95c8-11e9-9140-6908df90ca29.png)

**Comment by archonic** [comment]
That's an interesting issue. The icon helper relies on Gravatar's blank gif fallback, so Limestone is unaware of if Gravatar has an image for a given email. For that, I would have to integrate the Gravatar API, which I think would be a good idea.

**Comment by aeksco** [comment]
Interesting - wasn't familiar with how Gravatar handled that. We might be able to tackle it with a CSS-only solution and not implement the machinery to interface with the Gravatar API - not sure what the request overhead might be for that - i.e. we don't want to hit the Gravatar API from the backend each time a page loads :/

**Comment by archonic** [comment]
Updating the avatar will (or at least should) update the `updated_at` time on the user, and display of the user avatar and name should be cached. A css only solution would be preferable but I'm not sure how to incorporate it with gravatar. The way I solved a similar issue in my limestone based app was to remove gravatar so that the `has_attached?` method is a surefire way to tell if the user has an avatar.

Here's the fallback to gravatar which has it's own fallback to the blank gif. https://github.com/archonic/limestone/blob/master/app/helpers/icon_helper.rb#L12
